//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RCars {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RCars() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Resources.RCars", typeof(RCars).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string CreateBackToList {
            get {
                return ResourceManager.GetString("CreateBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string CreateCar {
            get {
                return ResourceManager.GetString("CreateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateCreate {
            get {
                return ResourceManager.GetString("CreateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG installation.
        /// </summary>
        public static string CreateLpgInstallation {
            get {
                return ResourceManager.GetString("CreateLpgInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. ODB32.
        /// </summary>
        public static string CreateLpgModelHolder {
            get {
                return ResourceManager.GetString("CreateLpgModelHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. BRC.
        /// </summary>
        public static string CreateLpgProducerHolder {
            get {
                return ResourceManager.GetString("CreateLpgProducerHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string CreateModel {
            get {
                return ResourceManager.GetString("CreateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Fabia.
        /// </summary>
        public static string CreateModelHolder {
            get {
                return ResourceManager.GetString("CreateModelHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new car.
        /// </summary>
        public static string CreateNewCar {
            get {
                return ResourceManager.GetString("CreateNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string CreateProducer {
            get {
                return ResourceManager.GetString("CreateProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Skoda.
        /// </summary>
        public static string CreateProducerHolder {
            get {
                return ResourceManager.GetString("CreateProducerHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required information.
        /// </summary>
        public static string CreateRequired {
            get {
                return ResourceManager.GetString("CreateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. 2000.
        /// </summary>
        public static string CreateYearHolder {
            get {
                return ResourceManager.GetString("CreateYearHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DeleteClose {
            get {
                return ResourceManager.GetString("DeleteClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDelete {
            get {
                return ResourceManager.GetString("DeleteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DetailsClose {
            get {
                return ResourceManager.GetString("DetailsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DetailsDelete {
            get {
                return ResourceManager.GetString("DetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsDetails {
            get {
                return ResourceManager.GetString("DetailsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DetailsEdit {
            get {
                return ResourceManager.GetString("DetailsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit car.
        /// </summary>
        public static string EditEditCar {
            get {
                return ResourceManager.GetString("EditEditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string IndexActions {
            get {
                return ResourceManager.GetString("IndexActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string IndexDelete {
            get {
                return ResourceManager.GetString("IndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string IndexDetails {
            get {
                return ResourceManager.GetString("IndexDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IndexEdit {
            get {
                return ResourceManager.GetString("IndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string IndexEntries {
            get {
                return ResourceManager.GetString("IndexEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG installation manufacturer.
        /// </summary>
        public static string IndexLPGManufacturer {
            get {
                return ResourceManager.GetString("IndexLPGManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG installation model.
        /// </summary>
        public static string IndexLPGModel {
            get {
                return ResourceManager.GetString("IndexLPGModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string IndexManufacturer {
            get {
                return ResourceManager.GetString("IndexManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string IndexModel {
            get {
                return ResourceManager.GetString("IndexModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string IndexOf {
            get {
                return ResourceManager.GetString("IndexOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production year.
        /// </summary>
        public static string IndexProductionYear {
            get {
                return ResourceManager.GetString("IndexProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search car.
        /// </summary>
        public static string IndexSearch {
            get {
                return ResourceManager.GetString("IndexSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        public static string IndexSearchPlaceholder {
            get {
                return ResourceManager.GetString("IndexSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string IndexShowing {
            get {
                return ResourceManager.GetString("IndexShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars table.
        /// </summary>
        public static string IndexTableTitle {
            get {
                return ResourceManager.GetString("IndexTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of cars.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string IndexTo {
            get {
                return ResourceManager.GetString("IndexTo", resourceCulture);
            }
        }
    }
}
