//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Resources.RError", typeof(RError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter LPG installation manufacturer..
        /// </summary>
        public static string CarLpgManufacturerRequired {
            get {
                return ResourceManager.GetString("CarLpgManufacturerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter LPG installation model..
        /// </summary>
        public static string CarLpgModelRequired {
            get {
                return ResourceManager.GetString("CarLpgModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter car manufacturer..
        /// </summary>
        public static string CarManufacturerRequired {
            get {
                return ResourceManager.GetString("CarManufacturerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter car model..
        /// </summary>
        public static string CarModelRequired {
            get {
                return ResourceManager.GetString("CarModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like car was not found....
        /// </summary>
        public static string CarNotFound {
            get {
                return ResourceManager.GetString("CarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date cannot be from future, bigger than.
        /// </summary>
        public static string CarProductionFuture {
            get {
                return ResourceManager.GetString("CarProductionFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date cannot be smaller than.
        /// </summary>
        public static string CarProductionPast {
            get {
                return ResourceManager.GetString("CarProductionPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter car production year..
        /// </summary>
        public static string CarYearRequired {
            get {
                return ResourceManager.GetString("CarYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter fuel amount..
        /// </summary>
        public static string ReceiptAmount {
            get {
                return ResourceManager.GetString("ReceiptAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be longer than 255 characters..
        /// </summary>
        public static string ReceiptComment {
            get {
                return ResourceManager.GetString("ReceiptComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date of refueling..
        /// </summary>
        public static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter distance from last refueling..
        /// </summary>
        public static string ReceiptDistance {
            get {
                return ResourceManager.GetString("ReceiptDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like fuel receipt was not found....
        /// </summary>
        public static string ReceiptNotFound {
            get {
                return ResourceManager.GetString("ReceiptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter fuel price..
        /// </summary>
        public static string ReceiptPrice {
            get {
                return ResourceManager.GetString("ReceiptPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter fuel type..
        /// </summary>
        public static string ReceiptType {
            get {
                return ResourceManager.GetString("ReceiptType", resourceCulture);
            }
        }
    }
}
