//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RLogging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RLogging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Resources.RLogging", typeof(RLogging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date.
        /// </summary>
        public static string LogsActionDate {
            get {
                return ResourceManager.GetString("LogsActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action duration [ms].
        /// </summary>
        public static string LogsActionDuration {
            get {
                return ResourceManager.GetString("LogsActionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string LogsEntries {
            get {
                return ResourceManager.GetString("LogsEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log message.
        /// </summary>
        public static string LogsMessage {
            get {
                return ResourceManager.GetString("LogsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string LogsOf {
            get {
                return ResourceManager.GetString("LogsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LogsSearch {
            get {
                return ResourceManager.GetString("LogsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        public static string LogsSearchPlaceholder {
            get {
                return ResourceManager.GetString("LogsSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string LogsShowing {
            get {
                return ResourceManager.GetString("LogsShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity logs list.
        /// </summary>
        public static string LogsTableTitle {
            get {
                return ResourceManager.GetString("LogsTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User activity logs.
        /// </summary>
        public static string LogsTitle {
            get {
                return ResourceManager.GetString("LogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string LogsTo {
            get {
                return ResourceManager.GetString("LogsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LogsUser {
            get {
                return ResourceManager.GetString("LogsUser", resourceCulture);
            }
        }
    }
}
