//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Resources.RModels", typeof(RModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG installation manufacturer.
        /// </summary>
        public static string CarLpgInstallationManufacturer {
            get {
                return ResourceManager.GetString("CarLpgInstallationManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG installation model.
        /// </summary>
        public static string CarLpgInstallationModel {
            get {
                return ResourceManager.GetString("CarLpgInstallationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string CarManufacturer {
            get {
                return ResourceManager.GetString("CarManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production year.
        /// </summary>
        public static string CarProductionYear {
            get {
                return ResourceManager.GetString("CarProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car ID.
        /// </summary>
        public static string ReceiptCarId {
            get {
                return ResourceManager.GetString("ReceiptCarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ReceiptComment {
            get {
                return ResourceManager.GetString("ReceiptComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption/100 km.
        /// </summary>
        public static string ReceiptConsumption {
            get {
                return ResourceManager.GetString("ReceiptConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance on the tank.
        /// </summary>
        public static string ReceiptDistanceOnTank {
            get {
                return ResourceManager.GetString("ReceiptDistanceOnTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel amount.
        /// </summary>
        public static string ReceiptFuelAmount {
            get {
                return ResourceManager.GetString("ReceiptFuelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel price.
        /// </summary>
        public static string ReceiptFuelPrice {
            get {
                return ResourceManager.GetString("ReceiptFuelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type.
        /// </summary>
        public static string ReceiptFuelType {
            get {
                return ResourceManager.GetString("ReceiptFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol station name.
        /// </summary>
        public static string ReceiptPetrolStationName {
            get {
                return ResourceManager.GetString("ReceiptPetrolStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refueling date.
        /// </summary>
        public static string ReceiptRefuellingDate {
            get {
                return ResourceManager.GetString("ReceiptRefuellingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price/100 km.
        /// </summary>
        public static string ReceiptTotalPrice {
            get {
                return ResourceManager.GetString("ReceiptTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string ReportEndDate {
            get {
                return ResourceManager.GetString("ReportEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string ReportStartDate {
            get {
                return ResourceManager.GetString("ReportStartDate", resourceCulture);
            }
        }
    }
}
