//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RChart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RChart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Content.Resources.RChart", typeof(RChart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data.
        /// </summary>
        public static string ChartAllData {
            get {
                return ResourceManager.GetString("ChartAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Lpg Consumption.
        /// </summary>
        public static string ChartAvgCons {
            get {
                return ResourceManager.GetString("ChartAvgCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price (for 100 km).
        /// </summary>
        public static string ChartAvgPrice {
            get {
                return ResourceManager.GetString("ChartAvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report.
        /// </summary>
        public static string ChartGenerateReport {
            get {
                return ResourceManager.GetString("ChartGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel consumption and price graph.
        /// </summary>
        public static string ChartGraphTitle {
            get {
                return ResourceManager.GetString("ChartGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string ChartLabelCons {
            get {
                return ResourceManager.GetString("ChartLabelCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuelling date.
        /// </summary>
        public static string ChartLabelDate {
            get {
                return ResourceManager.GetString("ChartLabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to litres.
        /// </summary>
        public static string ChartLabelLitres {
            get {
                return ResourceManager.GetString("ChartLabelLitres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ChartLabelPrice {
            get {
                return ResourceManager.GetString("ChartLabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal Lpg consumption.
        /// </summary>
        public static string ChartMaxCons {
            get {
                return ResourceManager.GetString("ChartMaxCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal Lpg consumption.
        /// </summary>
        public static string ChartMinCons {
            get {
                return ResourceManager.GetString("ChartMinCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date for data - .
        /// </summary>
        public static string ChartStartDate {
            get {
                return ResourceManager.GetString("ChartStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG consumption for 100 km.
        /// </summary>
        public static string ChartTextLpgCons {
            get {
                return ResourceManager.GetString("ChartTextLpgCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG consumption and average price for 100 km.
        /// </summary>
        public static string ChartTextLpgConsPrice {
            get {
                return ResourceManager.GetString("ChartTextLpgConsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG average price for 100 km.
        /// </summary>
        public static string ChartTextLpgPrice {
            get {
                return ResourceManager.GetString("ChartTextLpgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol consumption and average price for 100 km.
        /// </summary>
        public static string ChartTextPetrolConsPrice {
            get {
                return ResourceManager.GetString("ChartTextPetrolConsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel graphs for.
        /// </summary>
        public static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total distance on Lpg.
        /// </summary>
        public static string ChartTotalDist {
            get {
                return ResourceManager.GetString("ChartTotalDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price for Lpg.
        /// </summary>
        public static string ChartTotalPrice {
            get {
                return ResourceManager.GetString("ChartTotalPrice", resourceCulture);
            }
        }
    }
}
