//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RFuelReceipts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RFuelReceipts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Content.Resources.RFuelReceipts", typeof(RFuelReceipts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string CreateBackToList {
            get {
                return ResourceManager.GetString("CreateBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comment.
        /// </summary>
        public static string CreateCommandPlaceholder {
            get {
                return ResourceManager.GetString("CreateCommandPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateCreate {
            get {
                return ResourceManager.GetString("CreateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. 456.23.
        /// </summary>
        public static string CreateDistancePlaceholder {
            get {
                return ResourceManager.GetString("CreateDistancePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. 23.56.
        /// </summary>
        public static string CreateFuelAmountPlaceholder {
            get {
                return ResourceManager.GetString("CreateFuelAmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. 2.99.
        /// </summary>
        public static string CreateFuelPricePlaceholder {
            get {
                return ResourceManager.GetString("CreateFuelPricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new fuel receipt for.
        /// </summary>
        public static string CreateNewReceipt {
            get {
                return ResourceManager.GetString("CreateNewReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required information.
        /// </summary>
        public static string CreateRequired {
            get {
                return ResourceManager.GetString("CreateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Shell.
        /// </summary>
        public static string CreateStationPlaceholder {
            get {
                return ResourceManager.GetString("CreateStationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DeleteClose {
            get {
                return ResourceManager.GetString("DeleteClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDelete {
            get {
                return ResourceManager.GetString("DeleteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this receipt?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DetailsClose {
            get {
                return ResourceManager.GetString("DetailsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DetailsDelete {
            get {
                return ResourceManager.GetString("DetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsDetails {
            get {
                return ResourceManager.GetString("DetailsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DetailsEdit {
            get {
                return ResourceManager.GetString("DetailsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string DetailsReceipt {
            get {
                return ResourceManager.GetString("DetailsReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit fuel receipt for.
        /// </summary>
        public static string EditEditReceipt {
            get {
                return ResourceManager.GetString("EditEditReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string IndexActions {
            get {
                return ResourceManager.GetString("IndexActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption per 100 km.
        /// </summary>
        public static string IndexConsumption {
            get {
                return ResourceManager.GetString("IndexConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string IndexDate {
            get {
                return ResourceManager.GetString("IndexDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string IndexDelete {
            get {
                return ResourceManager.GetString("IndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string IndexDetails {
            get {
                return ResourceManager.GetString("IndexDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IndexEdit {
            get {
                return ResourceManager.GetString("IndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string IndexEntries {
            get {
                return ResourceManager.GetString("IndexEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel amount.
        /// </summary>
        public static string IndexFuelAmount {
            get {
                return ResourceManager.GetString("IndexFuelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel price.
        /// </summary>
        public static string IndexFuelPrice {
            get {
                return ResourceManager.GetString("IndexFuelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string IndexOf {
            get {
                return ResourceManager.GetString("IndexOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search fuel receipts.
        /// </summary>
        public static string IndexSearch {
            get {
                return ResourceManager.GetString("IndexSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        public static string IndexSearchPlaceholder {
            get {
                return ResourceManager.GetString("IndexSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string IndexShowing {
            get {
                return ResourceManager.GetString("IndexShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station name.
        /// </summary>
        public static string IndexStationName {
            get {
                return ResourceManager.GetString("IndexStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel receipts table.
        /// </summary>
        public static string IndexTableTitle {
            get {
                return ResourceManager.GetString("IndexTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of fuel receipts for.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string IndexTo {
            get {
                return ResourceManager.GetString("IndexTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price per 100 km.
        /// </summary>
        public static string IndexTotalPrice {
            get {
                return ResourceManager.GetString("IndexTotalPrice", resourceCulture);
            }
        }
    }
}
