//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpgConsumptionCostCalculator.Web.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpgConsumptionCostCalculator.Web.Content.Resources.RReport", typeof(RReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHOR.
        /// </summary>
        public static string PdfAuthor {
            get {
                return ResourceManager.GetString("PdfAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVERAGE LPG CONSUMPTION.
        /// </summary>
        public static string PdfAvgCons {
            get {
                return ResourceManager.GetString("PdfAvgCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVERAGE PRICE (for 100 km).
        /// </summary>
        public static string PdfAvgPrice {
            get {
                return ResourceManager.GetString("PdfAvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSUMPTION FOR 100 KM.
        /// </summary>
        public static string PdfCons {
            get {
                return ResourceManager.GetString("PdfCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string PdfDate {
            get {
                return ResourceManager.GetString("PdfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTANCE.
        /// </summary>
        public static string PdfDistance {
            get {
                return ResourceManager.GetString("PdfDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL AMOUNT.
        /// </summary>
        public static string PdfFuelAmount {
            get {
                return ResourceManager.GetString("PdfFuelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL CHART.
        /// </summary>
        public static string PdfFuelChart {
            get {
                return ResourceManager.GetString("PdfFuelChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL PRICE.
        /// </summary>
        public static string PdfFuelPrice {
            get {
                return ResourceManager.GetString("PdfFuelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL RECEIPTS LIST.
        /// </summary>
        public static string PdfFuelRecList {
            get {
                return ResourceManager.GetString("PdfFuelRecList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL TYPE.
        /// </summary>
        public static string PdfFuelType {
            get {
                return ResourceManager.GetString("PdfFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED.
        /// </summary>
        public static string PdfGenerated {
            get {
                return ResourceManager.GetString("PdfGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG consumption for 100 km.
        /// </summary>
        public static string PdfLpgCons {
            get {
                return ResourceManager.GetString("PdfLpgCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMAL LPG CONSUMPTION.
        /// </summary>
        public static string PdfMaxCons {
            get {
                return ResourceManager.GetString("PdfMaxCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMAL LPG CONSUMPTION.
        /// </summary>
        public static string PdfMinCons {
            get {
                return ResourceManager.GetString("PdfMinCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETROL STATION NAME.
        /// </summary>
        public static string PdfPetrolStationName {
            get {
                return ResourceManager.GetString("PdfPetrolStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE FOR 100 KM.
        /// </summary>
        public static string PdfPrice {
            get {
                return ResourceManager.GetString("PdfPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT FOR.
        /// </summary>
        public static string PdfReport {
            get {
                return ResourceManager.GetString("PdfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY.
        /// </summary>
        public static string PdfSummary {
            get {
                return ResourceManager.GetString("PdfSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL DISTANCE ON LPG.
        /// </summary>
        public static string PdfTotDist {
            get {
                return ResourceManager.GetString("PdfTotDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PRICE FOR LPG.
        /// </summary>
        public static string PdfTotPrice {
            get {
                return ResourceManager.GetString("PdfTotPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ReportClose {
            get {
                return ResourceManager.GetString("ReportClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date range for a report.
        /// </summary>
        public static string ReportDataRange {
            get {
                return ResourceManager.GetString("ReportDataRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string ReportExportCSV {
            get {
                return ResourceManager.GetString("ReportExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string ReportExportPDF {
            get {
                return ResourceManager.GetString("ReportExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
    }
}
